name: Lint and Test alogythms

on:
  push: { branches-ignore: [main] }
  pull_request: { branches-ignore: [main] }

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint '**/*.md'

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint Python files
        run: flake8 .

  sync-algo:
    needs: [lint-markdown, lint-python]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout backend branch into 'backend' directory
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          path: ${{ github.ref_name }}

      - name: Remove unnessary files
        run: |
          rm -rf ./${{ github.ref_name }}/.git
          rm -rf ./${{ github.ref_name }}/.github

      - name: Commit changes
        run: |
          git add ${{ github.ref_name }}
          git commit -m "Sync ${{ github.ref_name }} code to main/${{ github.ref_name }}" || echo "No changes to commit"

      - name: Push changes to main branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
